### ISSUE TITLE
ID3 or C4.5?

### ISSUE THREAD

**Issue by xautjzd** [sanity/quickml#108]
First, Thank you very much for providing such nice simple decisiontree API. But I have some questions about it. I have read the document, only know it's decisiontree API.But I don't know how to generate the decisiontree. Is it ID3 or C4.5, or any other else？ @sanity

**Comment by athawk81** [comment]
Hi Xautjzd,

the algorithm is essentially C4.5.  I.e. it conforms to the psudo-code on the wikipedia page about C4.5 (http://en.wikipedia.org/wiki/C4.5_algorithm).  However, it has hyper parameters one can modify to produce better trees / random forests.  

Alex
