### ISSUE TITLE
QuickML brings in Mahout and all its dependencies for use of a single Auc class

### ISSUE THREAD

**Issue by rbolkey** [sanity/quickml#119]
Having some troubles because QuickML depends upon mahout-core, which has an enormous number of (many outdated) dependencies. It appears to be a dependency only because QuickML uses the Auc class from Mahout. It may be better to cut that dependency and supply our own implementation.

**Comment by sanity** [comment]
Agreed, or as an interim measure, just remove the code that calls AUC and let anyone that needs it add it back.

**Comment by Zero3** [comment]
+1. The number of (indirect) dependencies is ridiculous. I didn't count them, but they added ~30 MB (!) .jar files to my project, many causing Maven warnings about overlapping classes.

**Comment by athawk81** [comment]
this has been resolved.
