### ISSUE TITLE
RandomDecisionForest results are very different from Weka

### ISSUE THREAD

**Issue by bardhlohaj** [sanity/quickml#131]
I implemented RandomDecisionForest and the results that I'm getting (using getProbability on RandomDecisionForest) are totally different from the results that I get on Weka(http://www.cs.waikato.ac.nz/ml/weka/).

Can you inform me if there is an issue on the RandomDecisionForest implementation or any specific way of how I should set the parameters of the DecisionTreeBuilder and RandomDecisionForest so I can get the same results as on Weka?

**Comment by sanity** [comment]
Can you elaborate on what you mean by "very different"?

Have you assessed the predictive accuracy of the results relative to Weka (eg. using RMSE)?

**Comment by athawk81** [comment]
bardhlohaj, the discrepancy is most certainly coming from different default settings and perhaps slight algorithmic variations.  RandomDecisionForestBuilder takes a DecisionTreeBuiler as an argument.  The defaults hyperparameters for DecisionTreeBuilder are very simple (and probably inappropriate for most data sets)...but they are exceptionally flexible (more so than Weks'a) and automatically tunable with the PredictiveModelOptimizer.
