### ISSUE TITLE
Documentation on quickml.org is possibly outdated

### ISSUE THREAD

**Issue by tarjeir** [sanity/quickml#133]
This line: 
final RandomForest randomForest = new RandomForestBuilder().buildPredictiveModel(irisDataset);

RandomForestBuilder is an abstract class in 0.9.4

Should probably be replaced by something like this (or simpler):

final RandomDecisionForest randomForest =new RandomDecisionForestBuilder<>(new DecisionTreeBuilder<>()
                .scorerFactory(new GRPenalizedGiniImpurityScorerFactory(1.0))
                .maxDepth(8)
                .minAttributeValueOccurences(0)
                .attributeIgnoringStrategy(new IgnoreAttributesWithConstantProbability(0.2)))
                .numTrees(2)
                .buildPredictiveModel(irisDataset);

Tarjei

**Comment by athawk81** [comment]
which file has this problem?  Thanks for your help btw.

**Comment by tarjeir** [comment]
Sorry for not stating that 100% clear: It is the quickml.org front page.

BR

Tarjei

**Comment by sanity** [comment]
@tarjeir You are very welcome to submit a pull request, the site is maintained in the gh-pages branch.  I'm currently on the road so it may be a few days before I can fix this.

**Comment by athawk81** [comment]
just pushed effectively the change Tarjei requested.
